small fixes

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -14,7 +14,7 @@ echo ''
 source "$DOTFILES_ROOT/util/interactive"
 
 setup_gitconfig () {
-  if ! [ -f git/gitconfig.symlink ]
+  if ! [ -f git/gitconfig.local.symlink ]
   then
     info 'setup gitconfig'
 
@@ -52,16 +52,16 @@ setup_gitconfig
 install_dotfiles
 
 # If we're on a Mac, let's install and setup homebrew.
-if [ "$(uname -s)" == "Darwin" ]
-then
-  info "installing dependencies"
-  if source bin/dot > /tmp/dotfiles-dot 2>&1
-  then
-    success "dependencies installed"
-  else
-    fail "error installing dependencies"
-  fi
-fi
+#if [ "$(uname -s)" == "Darwin" ]
+#then
+  #info "installing dependencies"
+  #if source bin/dot > /tmp/dotfiles-dot 2>&1
+  #then
+  #  success "dependencies installed"
+  #else
+  #  fail "error installing dependencies"
+  #fi
+#fi
 
 echo ''
-echo '  All installed!'
+echo '  All bootstrapped!'
